### ISSUE TITLE
Does not Compile with g++

### ISSUE THREAD

**Issue by ttbek** [cnettel/cnF2freq#4]
The c++ file does not compile as described in the demo.sh file with g++
```
g++ --version
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
Not everyone has icc, nor wants to install their suite for just the compiler https://software.intel.com/en-us/intel-parallel-studio-xe and some may need to pay that 700$ for it.  

Consider fixing the code and/or providing binary versions for common platforms (e.g. Windows, OSX, and at least 1 or 2 common Linux Distros, e.g. Ubuntu, Fedora, Redhat,...).  More complete support could include BSD and Solaris, if you want to be really thorough Haiku, Rust OS etc..

**Comment by cnettel** [comment]
g++ should certainly work. Can you please confirm which branch this was on? Chaplink_maxsat?

What version of boost did you use? (The standard one in Ubunt 16.04, I would guess?)

**Comment by ttbek** [comment]
Yes, the main branch, I believe it is Chaplink_maxsat.  Yes, the standard one in Ubuntu 16.04:
```
dpkg -s libboost-dev | grep 'Version'
Version: 1.58.0.1ubuntu1
```
Ways I have tried: 
```
g++ -O2 cnF2freq.cpp -ffast-math  -o cnF2freq -fopenmp -I boost_1_57_0 -g &> compile_exact_line
g++ -O2 cnF2freq.cpp -ffast-math  -o cnF2freq -fopenmp -I boost_1_58_0 -g &> compile_v_1_58_0
g++ -O2 cnF2freq.cpp -ffast-math  -o cnF2freq -fopenmp -I boost_1_57_0 -g -std=c++11 &> compile_c++11
g++ -O2 cnF2freq.cpp -ffast-math  -o cnF2freq -fopenmp -I boost_1_58_0 -g -std=c++11 &> compile_v_1_58_0_c++11
g++ -O2 cnF2freq.cpp -ffast-math  -o cnF2freq -fopenmp -I boost_1_57_0 -g -std=c++14 &> compile_c++14
g++ -O2 cnF2freq.cpp -ffast-math  -o cnF2freq -fopenmp -I boost_1_58_0 -g -std=c++14 &> compile_v_1_58_0_c++14
```
Files are attached, renamed to .txt so github would accept the upload.  

[compile_exact_line.txt](https://github.com/cnettel/cnF2freq/files/1245597/compile_exact_line.txt)
[compile_v_1_58_0.txt](https://github.com/cnettel/cnF2freq/files/1245600/compile_v_1_58_0.txt)
[compile_c++11.txt](https://github.com/cnettel/cnF2freq/files/1245602/compile_c.11.txt)
[compile_v_1_58_0_c++11.txt](https://github.com/cnettel/cnF2freq/files/1245605/compile_v_1_58_0_c.11.txt)
[compile_c++14.txt](https://github.com/cnettel/cnF2freq/files/1245607/compile_c.14.txt)
[compile_v_1_58_0_c++14.txt](https://github.com/cnettel/cnF2freq/files/1245608/compile_v_1_58_0_c.14.txt)

Edit: We tried on two systems, identical results.  



.

**Comment by cnettel** [comment]
OK, the demo.sh is updated to include a define which is needed for GCC compatibility and some other flag changes. A minor _isnan issue is also fixed. Parsing support for another input format also necessitates boost 1.61. It is possible that by undeffing READHAPSSAMPLE in settings.h you can avoid that dependency, but bringing >= boost 1.61 in is easier for sure.

**Comment by cnettel** [comment]
I realized there are some linker flags missing as well. I need to recheck those in my local build environment. Expect an update in the next few days.

**Comment by ttbek** [comment]
Hi there, it should be working now then?  I will try again, with boost 1.61 this time.

**Comment by ttbek** [comment]
In the new demo.sh is not quite correct, you are missing a space (' ') between "--fast-math" and "-fopenmp.":
g++ cnF2freq.cpp -O2 --fast-math-fopenmp -I boost_1_61_0 --std=c++14 -DDOEXTERNFORGCC -lboost_program_options -o cnF2freq

It should be: 
g++ cnF2freq.cpp -O2 --fast-math -fopenmp -I boost_1_61_0 --std=c++14 -DDOEXTERNFORGCC -lboost_program_options -o cnF2freq

For anyone with their boost library in a different location, you may need to specify the path to the boost_program_options library, as: 
g++ cnF2freq.cpp -O2 --fast-math -fopenmp -I boost_1_61_0 --std=c++14 -DDOEXTERNFORGCC -L/path/to/boost/libs -lboost_program_options -o cnF2freq

Or alternatively the full name of the library can be given directly: 
g++ cnF2freq.cpp -O2 --fast-math -fopenmp -I boost_1_61_0 --std=c++14 -DDOEXTERNFORGCC  /path/to/libs/libboost_program_options.a -o cnF2freq

For a concrete example, I installed boost to /home/kunji/Boost/Boost/ and my Boost root is in /home/kunji/Boost/boost_1_61_0.  So I compiled as: 
g++ cnF2freq.cpp -O2 --fast-math -fopenmp -I /home/kunji/Boost/boost_1_61_0 --std=c++14 -DDOEXTERNFORGCC /home/kunji/Boost/Boost/lib/libboost_program_options.a -o cnF2freq

I consider this issue closed once the space is added to the compile line.  Thanks very much for helping me get this running (well... so far I only compiled it, hopefully it runs for me ^_^, I'll raise new issues if I face problems with it).

**Comment by ttbek** [comment]
Compile line is fixed in demo.sh
